#!/bin/sh

### BEGIN INIT INFO
# Provides:   edo365board
# Required-Start:    nginx
# Required-Stop:     nginx
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       edo365board folder reader
### END INIT INFO


# include functions
. /etc/init.d/functions

# read config
if test -e "/etc/edo365board.conf"; then 
    while read -r SERVERNAME USER; 
        do C_EXIST=true; 
    done < "/etc/edo365board.conf"
else 


start() {
        initlog -c "echo -n Starting edo365board watcher: "
        /usr/bin/edo365watchfolder --target /var/www/$SERVERNAME/listing.json --watch /samba/$USER/public/ &
        ### Create the lock file ###
        touch /var/lock/subsys/edo365board
        success $"edo365board startup"
        echo
}

# Restart the service 
stop() {
        initlog -c "echo -n Stopping edo365board watcher: "
        killproc edo365watchfolder
        ### Now, delete the lock file ###
        rm -f /var/lock/subsys/edo365board
        echo
}



### main logic ###
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status_of_proc -p $PID "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0