#!/bin/sh
wget -q https://packages.microsoft.com/keys/microsoft.asc -O- | apt -key add -
add-apt-repository "deb [arch=amd64] https://packages.microsoft.com    /repos/vscode stable main"
#sudo apt-get -y  install code
