#!/bin/sh

# change nginx config
cat | ed /etc/nginx/nginx.conf <<EOF 
/.*server_names_hash_bucket_size
c
server_names_hash_bucket_size 64;
.
w
q
EOF

systemctl reload nginx
systemctl status nginx

# firewall settings
ufw allow ssh
ufw allow 'Nginx Full'
ufw disable
ufw enable
ufw status

# enable php
add-apt-repository ppa:ondrej/php -y